const foodOptions = [
		{ name: "Big Mac (McDonald's)", calories: 550, emoji: "🍔" },
		{ name: "Whopper (Burger King)", calories: 657, emoji: "🍔" },
		{ name: "Chick-fil-A Chicken Sandwich", calories: 440, emoji: "🍗" },
		{ name: "Starbucks Frappuccino (Grande)", calories: 370, emoji: "☕" },
		{ name: "Domino's Cheese Pizza (1 slice)", calories: 290, emoji: "🍕" },
		{ name: "Subway Footlong Turkey Sandwich", calories: 480, emoji: "🥪" },
		{ name: "Taco Bell Crunchy Taco", calories: 170, emoji: "🌮" },
		{ name: "Dunkin' Glazed Donut", calories: 260, emoji: "🍩" },
		{ name: "KFC Original Recipe Chicken (Drumstick)", calories: 120, emoji: "🍗" },
		{ name: "Chipotle Chicken Burrito", calories: 1045, emoji: "🌯" },
		{ name: "McDonald's Egg McMuffin", calories: 300, emoji: "🥚" },
		{ name: "Starbucks Blueberry Muffin", calories: 320, emoji: "🫐" },
		{ name: "Five Guys Cheeseburger", calories: 840, emoji: "🍔" },
		{ name: "Panera Bread Broccoli Cheddar Soup (Bowl)", calories: 360, emoji: "🥣" },
		{ name: "Pizza Hut Pepperoni Pizza (1 slice)", calories: 300, emoji: "🍕" },
		{ name: "McDonald's Fries (Medium)", calories: 340, emoji: "🍟" },
		{ name: "Krispy Kreme Original Glazed Doughnut", calories: 190, emoji: "🍩" },
		{ name: "Shake Shack ShackBurger", calories: 530, emoji: "🍔" },
		{ name: "Wendy's Frosty (Small)", calories: 340, emoji: "🍦" },
		{ name: "In-N-Out Double-Double Burger", calories: 670, emoji: "🍔" },
		{ name: "Popeyes Spicy Chicken Sandwich", calories: 700, emoji: "🍗" },
		{ name: "Burger King Onion Rings (Medium)", calories: 410, emoji: "🧅" },
		{ name: "McDonald's Hot Fudge Sundae", calories: 330, emoji: "🍨" },
		{ name: "Starbucks Chocolate Croissant", calories: 350, emoji: "🥐" },
		{ name: "Domino's Chicken Wings (6 pieces)", calories: 450, emoji: "🍗" },
		{ name: "Subway Veggie Delight (6-inch)", calories: 230, emoji: "🥗" },
		{ name: "Chipotle Guacamole (1 serving)", calories: 230, emoji: "🥑" },
		{ name: "Taco Bell Chicken Quesadilla", calories: 510, emoji: "🌮" },
		{ name: "Dunkin' Bagel with Cream Cheese", calories: 450, emoji: "🥯" },
		{ name: "Panera Bread Chicken Caesar Salad", calories: 440, emoji: "🥗" },
		// New low-calorie options
		{ name: "Coca-Cola (Can)", calories: 140, emoji: "🥤" },
		{ name: "Diet Coke (Can)", calories: 1, emoji: "🥤" },
		{ name: "Apple Slices (McDonald's)", calories: 15, emoji: "🍏" },
		{ name: "KFC Grilled Chicken Breast", calories: 90, emoji: "🍗" },
		{ name: "McDonald's Small Coffee (Black)", calories: 0, emoji: "☕" },
		{ name: "Subway Apple Slices", calories: 35, emoji: "🍏" },
		{ name: "Starbucks Americano (Tall)", calories: 10, emoji: "☕" }
];
