function calculateAndSuggest() {
		const distance = parseFloat(document.getElementById('distance').value);
		const resultDiv = document.getElementById('result');
		resultDiv.innerHTML = ''; // Clear previous results

		if (isNaN(distance) || distance <= 0) {
				resultDiv.innerHTML = '<p class="text-red-600 font-medium fade-in">Please enter a valid distance.</p>';
				return;
		}

		const caloriesBurned = calculateCaloriesBurned(distance);
		const co2PerKmMotorbike = 103; // grams of CO2 per kilometer for a motorbike
		const totalCO2Saved = (co2PerKmMotorbike * distance) / 1000; // converting grams to kilograms

		// Adding real-world equivalence for better understanding
		const treeAbsorptionRate = 21.77; // kg of CO2 absorbed by a tree per year
		const carEmissionsPerKm = 0.121; // average car emits 0.121 kg of CO2 per km
		const plasticBagCO2 = 0.01; // CO2 generated by producing 1 plastic bag (in kg)

		const hoursOfTreeAbsorption = (totalCO2Saved / treeAbsorptionRate) * 365 * 24; // convert to hours
		const carEquivalentKm = (totalCO2Saved / carEmissionsPerKm).toFixed(1); // km of driving equivalent
		const plasticBagsEquivalent = Math.round(totalCO2Saved / plasticBagCO2); // number of plastic bags produced

		// Generate the result HTML
		let resultHTML = `
				<div class="result-section mb-6 fade-in-slide-up">
						<h2 class="text-green-700 font-bold text-2xl mb-4">Congratulations! 🌍💚</h2>
						<p class="text-green-700 font-semibold text-lg">By cycling <strong>${distance} km</strong> instead of riding a motorbike, you saved <span class="highlight-co2 text-3xl">${totalCO2Saved.toFixed(2)} kg</span> of CO2!</p>
				</div>

				<div class="equivalent-section mb-6 fade-in-slide-up">
						<h3 class="text-green-600 font-bold text-xl mb-2">This is equivalent to:</h3>
						<ul class="list-disc pl-5 text-green-600 text-md">
								<li>What a tree absorbs in <strong>${hoursOfTreeAbsorption.toFixed(1)} hours</strong> 🌳</li>
								<li>Driving <strong>${carEquivalentKm} km</strong> in a car 🚗</li>
								<li>Producing <strong>${plasticBagsEquivalent} plastic bags</strong> 🛍️</li>
						</ul>
				</div>

				<div class="calories-section mb-6 fade-in-slide-up">
						<h3 class="text-indigo-700 font-bold text-xl">You've burned <span class="text-3xl">${caloriesBurned}</span> calories! 🔥🚴</h3>
				</div>

				<div class="food-section fade-in-slide-up">
						<h3 class="text-indigo-700 font-semibold mb-3">You've earned one of these: 🎉</h3>
						<div class="grid grid-cols-1 gap-4 food-list">
		`;

		// Generate food card suggestions
		const suggestedFoods = foodOptions.filter(food => food.calories <= caloriesBurned)
																			.sort((a, b) => b.calories - a.calories);

		if (suggestedFoods.length === 0) {
				resultHTML += '<p class="text-indigo-600 fade-in">No food options available for the calories burned. Great job on the intense ride! 💪</p>';
		} else {
				resultHTML += `
						<div class="grid grid-cols-1 gap-4 food-list">
								${suggestedFoods.map((food, index) => `
										<div class="food-card bg-white rounded-lg shadow-md p-4 flow-up fade-in-slide-up ${index === 0 ? 'first-item' : ''}" style="animation-delay: ${index * 0.1}s;">
												<div class="flex justify-between items-center">
														<span class="text-2xl">${food.emoji}</span>
														<span class="text-indigo-600 font-semibold">${food.calories} cal</span>
												</div>
												<h3 class="text-lg font-medium mt-2">${food.name}</h3>
										</div>
								`).join('')}
						</div>
				`;
		}

		resultDiv.innerHTML = resultHTML;
		createSparkles(resultDiv, 30); // Add 30 sparkles to the result container
}


// Add event listener for the Enter key
document.getElementById('distance').addEventListener('keypress', function(event) {
	if (event.key === 'Enter') {
			event.preventDefault(); // Prevent form submission if it's in a form
			calculateAndSuggest();
	}
});

// Add event listener for the button click
document.getElementById('calculateButton').addEventListener('click', calculateAndSuggest);


// Add event listener for the Enter key
document.getElementById('distance').addEventListener('keypress', function(event) {
	if (event.key === 'Enter') {
			event.preventDefault(); // Prevent form submission if it's in a form
			calculateAndSuggest();
	}
});

// Add event listener for the button click
document.getElementById('calculateButton').addEventListener('click', calculateAndSuggest);
